---
- set_fact:
    ansible_distro: "{{ ansible_distribution|lower|replace('\"', '') }}"
  become: true


- name: Install packages to allow apt to use a repository over HTTPS
  package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker’s official GPG key for ubuntu
  apt_key:
    state: present
    url:  https://download.docker.com/linux/ubuntu/gpg  
    id: 0EBFCD88
  become: true
  when: ansible_distribution == 'Ubuntu'


- name: Set up  the stable repository for ubuntu
  apt_repository:
    repo:  deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes
  become: true  
  when: ansible_distribution == 'Ubuntu'

  #- name: Install Docker CE
  #package:
  #  name: docker-ce
  #  state: latest
  #become: true


- name: Install docker-python for ansible interaction
  pip: name=docker-py
  become: true



  #- name: Add docker.socket file
  #  copy: src=docker.socket dest=/usr/lib/systemd/system/docker.socket
  #- name: Enable docker.socket
  #  raw: systemctl enable docker && systemctl start docker

- name: Making sure docker daemon is running.
  service:
    name: docker
    enabled: yes
    state: started





- name: Create the docker group
  group:
    name: docker
    state: present
  become: true

- name: add user to the group
  user:
    group: docker
    name: "{{ ansible_user }}"
  become: true

- name: Reload docker service
  service:
    state: reloaded
    name: docker
  become: true

- name: Start docker service
  service:
    state: restarted
    name: docker
  become: true

