---
- name: check status of /etc/default/ufs
  stat:
    path: /etc/default/ufw
  register: docker_ufw_stat

- name: ensure ufw forwarding is enabled
  lineinfile:
    dest: /etc/default/ufw
    regexp: ^DEFAULT_FORWARD_POLICY=
    line: DEFAULT_FORWARD_POLICY="ACCEPT"
    state: present
  when: docker_ufw_stat.stat.exists

- name: ensure linux-image-extra package is installed
  package:
    name: linux-image-extra-{{ ansible_kernel }}
    state: present
  register: docker_kernel_update
  ignore_errors: true

- name: ensure cgroup swap limit is enabled in grub
  lineinfile:
    dest: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
    state: present
  register: docker_grub_config

- name: update grub if necessary
  command: update-grub
  when: docker_grub_config|changed

- include: reboot.yml
  when: docker_kernel_update|changed or docker_grub_config|changed
